### ISSUE TITLE
Display batting averages

### ISSUE THREAD

**Issue by sussexrick** [stoolball-england/stoolball-org-uk#187]
- [x] Keep the old URL https://www.stoolball.org.uk/play/statistics/batting-average
- [x] The overall statistics page #114 should include the top ten averages plus a link to view all averages.
- [x] Link to to batting averages from the team statistics page #120
- [x] club statistics page #527 shows top ten and link to all
- [x] the location statistics page #97 shows the top ten batting averages and links to all
- [x] the season statistics page #85 shows top ten batting averages, and links to all
- [x] the competition statistics page #270 shows top ten batting averages, and links to all
- [x] Review data for Sean Power in 2018 on the old site as an example of confusing data. Average table says matches but means innings.
