### ISSUE TITLE
Display batting strike rate

### ISSUE THREAD

**Issue by sussexrick** [stoolball-england/stoolball-org-uk#188]
- [x] keep the old URL https://www.stoolball.org.uk/play/statistics/batting-strike-rate
- [x] the overall statistics page #114 should include a link to the top batting strike tests
- [x] Link to best batting strike rates from team statistics page #120 
- [x] club statistics page #527 shows link
- [x] the location statistics page #97 links to the best batting strike rates
- [x] the season statistics page #85 links to the best batting strike rates
- [x] the competition statistics page #270 links to the best batting strike rates
