### ISSUE TITLE
Display bowling average

### ISSUE THREAD

**Issue by sussexrick** [stoolball-england/stoolball-org-uk#189]
- [x] keep old URL https://www.stoolball.org.uk/play/statistics/bowling-average
- [x] the overall statistics page #114 should include the top ten best bowling averages and a link to all bowling averages
- [x] the team statistics page #120 links to bowling averages for the team
- [x] club statistics page #527 shows link to all
- [x] the location statistics page #97 shows the top ten bowling averages and links to all
- [x] the season statistics page #85 shows the top ten bowling averages and links to all
- [x] the competition statistics page #270 shows the top ten bowling averages and links to all
