### ISSUE TITLE
Display bowling strike rate

### ISSUE THREAD

**Issue by sussexrick** [stoolball-england/stoolball-org-uk#191]
- [x] keep the old URL https://www.stoolball.org.uk/play/statistics/bowling-strike-rate
- [x] the overall statistics page should include the top ten best strike rates and a link to all players' strike rates
- [x] the team statistics page #120 links to the bowling economy rates for the team
- [x] club statistics page #527 links to all
- [x] the location statistics page #97 shows the top ten bowling strike rates and links to all
- [x] the season statistics page #85 shows the top ten bowling strike rates and links to all
- [x] the competition statistics page #270 shows the top ten bowling strike rates and links to all
