### ISSUE TITLE
Display player performances

### ISSUE THREAD

**Issue by sussexrick** [stoolball-england/stoolball-org-uk#206]
- [x] Keep the old URL https://www.stoolball.org.uk/play/statistics/player-performances
- [x] the overall statistics page #114 should link to the full list of player performances, most recent first, from a heading of 'All-round performance statistics'
- [x] each player statistics summary page has text at the top saying they've played "xxx matches". That text should link to their player performances.
- [x] the team statistics page #120 links to all player performances for the team from the player of the match section
- [x] club statistics page #527 has link to all player performances at that location from the player of the match section
- [x] the location statistics page #97 links to all player performances at that location from the player of the match section
- [x] the season statistics page #85 links to all player performances at that location from the player of the match section
- [x] the competition statistics page #270 links to all player performances at that location from the player of the match section
- [x] support date filter #507

Screenshot from the old website:
![image](https://user-images.githubusercontent.com/1260550/191614061-ab8dd18f-8c22-48c7-a550-c933a6ef36ed.png)

Test support where the same player bats three times in the same innings, once as one identity and twice as another, in a multi-innings match.

* don't combine multiple batting innings, **not even by identity**, because there's no good way to represent multiple dismissals
* don't combine bowling figures, always do that by identity, because it wouldn't make sense to combine bowling figures but not batting
* don't combine player performances, always do that by identity, because it wouldn't make sense to combine bowling figures but not batting

This means the SQL query is a simple SELECT from the statistics table, no need for any GROUP BY to get the right data. 
 
- [x] if a player has multiple different names, show the player column without a link on the individual scores and bowling figures tables on the player's batting and bowling pages
