### ISSUE TITLE
Support filtering statistics by team

### ISSUE THREAD

**Issue by sussexrick** [stoolball-england/stoolball-org-uk#503]
Should be available on:
- [x] player summary
- [x] player batting
- [x] player bowling
- [x] player fielding
- [x] player catches
- [x] player run-outs
- [x] statistics page
- [x] club statistics page
- [x] match location statistics page
- [x] season statistics page
- [x] competition statistics page
- [x] highest individual scores #194 
- [x] best bowling performances #190 
- [x] player if the match #205 
- [x] player performances #206 
- [x] most runs #200
- [x] most wickets #204 
- [x] most catches #196 
- [x] most run-outs #199 
- [x] batting average #187 
- [x] batting strike rates #188 
- [x] bowling averages #189 
- [x] bowling economy #193 
- [x] bowling strike rates #191 
- [x] most player of the match awards #197
- [x] most scores of more than x #201 
- [x] most wicket hauls of x #202
- [x] On the old site the following issue exists, so ensure it's working correctly:

**Individual scores by team includes opposition**
This list should not include Nutley players and others...

https://www.stoolball.org.uk/play/statistics/individual-scores?team=1&from=1551398401&to=1569887999

![image](https://user-images.githubusercontent.com/1260550/198838975-cfe90fc3-ae2c-4523-afd0-00890b34ecb6.png)
