### ISSUE TITLE
Support filtering statistics by date

### ISSUE THREAD

**Issue by sussexrick** [stoolball-england/stoolball-org-uk#507]
Before and after dates. Validate that dates aren't in the future, and say we haven't got statistics from then!

Should be supported on:

- [x] player batting page #115 
- [x] player bowling page #116 
- [x] player fielding page #499 
- [x] highest individual scores #194 
- [x] best bowling performances #190 
- [x] catches #192 
- [x] run-outs #207
- [x] most runs #200
- [x] most wickets #204 
- [x] most catches #196 
- [x] most run-outs #199 
- [x] batting average #187 
- [x] batting strike rates #188 
- [x] bowling averages #189 
- [x] bowling economy #193 
- [x] bowling strike rates #191
